### ISSUE TITLE
Basic Privacy Crack Option - Is it a possibility?

### ISSUE THREAD

**Issue by gamo73uk** [travisgoodspeed/md380tools#154] opened 2016-06-22 07:17 UTC
Not sure how, or even if this could be implemented, but since BP only has 255 different possible keys,  would it be possible to have an option that you can have on a side button (like monitor etc.) which switches the front panel to display BP Key 00 then  allow you to use the up/down arrow to scroll through each possible BP key on that channel/tg etc. to slowly "brute-force" BP settings? 

You can only program 16 a time in to the radio for use on channels so setting up a 255 channel list to try each combination would take ages.

Unless someone knows of a way to do it in DSD+ or the like? ;-)

**Comment by travisgoodspeed** [comment] 2016-06-22 15:16
Basic Privacy and Enhanced Privacy can both be cracked, but I've never seen them used in the field and the Tytera algorithms are very different from the Motorola ones.

See #50 for Motorola Privacy compatibility.

**Comment by travisgoodspeed** [comment] 2016-07-08 14:55
Closing this as a duplicate of #50.

**Closed by travisgoodspeed** 2016-07-08 14:55 UTC
Labels: crypto, wish list

**Comment by abdullah612** [comment] 2017-09-17 22:49
any guide on how to crack them
