### ISSUE TITLE
Blank display issue after flashing MD380

### ISSUE THREAD

**Issue by on8vm** [travisgoodspeed/md380tools#424] opened 2016-10-02 20:27 UTC
After flashing my MD380 with the latest version, I occasionally have a blank display.

When the display becomes blank (just blue backlight), RX and TX work well.
I cannot reproduce the problem: it happens when just listening or when commuting memories.

Here below the build log (from http://pd0zry.nl/md380-fw/) of the firmware version I have used.

73, ON8VM

```
firmware-20161002-180001-1a1f1d15


```

**Comment by sijskes** [comment] 2016-10-02 20:51
could you please try the stable build at https://github.com/roelandjansen/md380tools/releases/latest/ and report back?

**Comment by on8vm** [comment] 2016-10-02 21:25
Thanks Simon,

just flashed with f62053f-MD380-experimental-firmware.bin you suggested.

I had the blank display issues already twice, by simply browsing the memories in a zone.

FYI I have enable users.csv (working fine!) and rogerbeep, while debug, promiscuous, experimental and devonly are disabled.

KR,
Vito

**Comment by sijskes** [comment] 2016-10-02 21:42
@on8vm thanks for reporting the settings. could you explain what you mean with browsing the memories in a zone means? do you do changing zones? or contacts?

**Comment by sijskes** [comment] 2016-10-02 21:44
@on8vm i just fixed a buffer overrun in user.csv popup. can you test without users.csv popup, or use the pre-release https://github.com/roelandjansen/md380tools/releases/tag/6d5a5f6

**Comment by on8vm** [comment] 2016-10-03 20:12
@sijskes I flashed my md380 with the latest fw you provided.
The blank display issue appeared again, with users.csv enabled.
FYI after flashing it with the new fw, I re-wrote the SPI flash with the newest users.csv (from a raspberry pi, using 2016-05-27-raspbian-jessie-lite).

I have now disabled users.csv feature and I'll test for a while.

tnx, on8vm

**Comment by sijskes** [comment] 2016-10-04 06:39
what do you mean with browsing the memories? turning the channel selector?

**Comment by on8vm** [comment] 2016-10-04 08:42
Yes, just this

**Comment by on8vm** [comment] 2016-10-04 17:47
Tested the fw at URL https://github.com/roelandjansen/md380tools/releases/tag/6d5a5f6: I have the blank display issue with and without enabling users.csv.

I have also noticed that the display changes color: yellow on the bottom part and reddish/brown on the main area. Switching off and on, it becomes blue again as usual...

It's not the first experimental fw I try on my (I've already tried 3 or 4 previous versions in June and July 2016) but it's first time I encounter this strange behavior of the display.

**Comment by on8vm** [comment] 2016-10-04 17:53
![photo 04-10-16 19 35 21](https://cloud.githubusercontent.com/assets/22579767/19085873/39809cca-8a6c-11e6-8b5c-56aa5c275b7b.jpg)

**Comment by on8vm** [comment] 2016-10-04 18:40
![photo 04-10-16 20 38 58](https://cloud.githubusercontent.com/assets/22579767/19087576/ca40fcfe-8a72-11e6-8985-e6ba49999b3c.jpg)

**Comment by sijskes** [comment] 2016-10-04 19:14
Yes. it is very strange. i've not seen this behaviour before. I will keep this issue open for others to comment. 
Maybe is your codeplug that somehow causes this behaviour. To exclude any hardware failure can you try on a other ham's md380 with the same users.csv codeplug and firmware version.

**Comment by on8vm** [comment] 2016-10-06 17:12
@sijskes 
I have put back the old firmware (firmware-20160727-170001-b17ce768.bin) and the blank and changing color display issues don't appear anymore...
I'm back to the "post-it" version do users.csv info display... I liked the full screen.

But now the display behavior is definitely stable...

KR,
ON8VM

**Comment by on8vm** [comment] 2016-10-07 19:14
Hello,

I'm uploading the codeplug I'm using now and in the past.
The one I was using with the latest firmwares, that caused the blank (and strange colors) screen issue on my MD380.
The same I'm using now with the older (27/7/2016) firmware (firmware-20160727-170001-b17ce768.bin).
 
(rename the file to .zip)

[20161004_ON8VM_TYT380_PMR_Analogue.txt](https://github.com/travisgoodspeed/md380tools/files/516935/20161004_ON8VM_TYT380_PMR_Analogue.txt)

**Comment by sijskes** [comment] 2016-10-07 21:44
@on8vm can you try this last one?

**Comment by on8vm** [comment] 2016-10-08 14:20
@sijskes 
Hi Simon,

Have you prepared a specific build available at https://github.com/roelandjansen/md380tools/releases/tag with the latest change?

Or your change is part of the latest build that everyone can use?
ex. downloading the bin http://pd0zry.nl/md380-fw/firmware-20161008-160001-6a75f895.bin or via a "sudo make all flash"?

I play with firmwares but I'm not really an expert in software/firmware development...

TNX, on8vm

**Comment by sijskes** [comment] 2016-10-08 15:01
No the repo of @roelandjansen is not up to date yet, for testing your specific problem, the latest from pd0rzy is fine.

**Comment by on8vm** [comment] 2016-10-09 05:50
@sijskes 
I tried the build of firmware-20161008-220001-1ed9b3d9.bin (08-Oct-2016 22:02).

I have always the same problems: blank display and altered colors (I can live with the last issue... the first is quite annoying).

![photo 09-10-16 07 26 35](https://cloud.githubusercontent.com/assets/22579767/19218225/f073a694-8df4-11e6-9e81-3fe9b9f071a1.jpg)
![photo 09-10-16 07 32 06](https://cloud.githubusercontent.com/assets/22579767/19218226/f0781bd4-8df4-11e6-9d71-e99db6be78db.jpg)
![photo 08-10-16 22 40 15](https://cloud.githubusercontent.com/assets/22579767/19218224/f072b68a-8df4-11e6-8517-b0bdddcf0772.jpg)

**Comment by on8vm** [comment] 2016-10-09 07:57
FYI the fw version I reverted to my md380 and that doesn't give any display problem:

![photo 09-10-16 09 55 14](https://cloud.githubusercontent.com/assets/22579767/19218945/b06af6f8-8e06-11e6-9919-ffec902dfc07.jpg)

**Comment by mach327** [comment] 2016-10-09 08:10
Using pd0zry's builds, the last firmware that does not exhibit this behavior on my VHF MD-380 is:
http://pd0zry.nl/md380-fw/firmware-20161008-130001-b8533dad.bin
and the first that does exhibit this behavior is:
http://pd0zry.nl/md380-fw/firmware-20161008-160001-6a75f895.bin

**Comment by ik2cnf** [comment] 2016-10-09 12:28
I acknowledge the same problem reported by mach327 on my UHF MD-380.

At start, screen is a white display but for channel number. Turning channels knob changes the number displayed, screen still white. (see pict 1)
Turning volume knob makes empty volume bar appear, but it remains on the sceen. (see pict 2)
Pressing menu button makes menu screen appear, but without icons. Pressing downkey button makes icon appear, one press down one icon. (see pict 3)
If you press exit key you never return to home page, last menu displayed still appears on screen.

I agree with mach37 that firmware-20161008-130001-b8533dad.bin from pd0rzy's builds is the latest working without problems.
![md380-home](https://cloud.githubusercontent.com/assets/20490854/19220386/5879d830-8e2c-11e6-9cea-61b2ee2c7780.png)
![md380-voume](https://cloud.githubusercontent.com/assets/20490854/19220388/6246c8b4-8e2c-11e6-9e6f-45049ff1b5a7.png)
![md380-menu](https://cloud.githubusercontent.com/assets/20490854/19220390/68d27e30-8e2c-11e6-9de7-79779527426d.png)
![md380-info](https://cloud.githubusercontent.com/assets/20490854/19220396/70e72666-8e2c-11e6-8f45-9f557283d00f.png)

**Comment by sijskes** [comment] 2016-10-09 12:33
@ik2cnf what settings do you use? debug? netmon? promisc?

**Comment by sijskes** [comment] 2016-10-09 12:35
@mach327 netmon display switching is far from perfect. ack.

**Comment by sijskes** [comment] 2016-10-09 12:35
a fix for this, is to disable netmon.

**Comment by sijskes** [comment] 2016-10-09 12:37
and also disable debug. netmon and debug are developer features. some incompletness is to be exptected.

**Comment by ik2cnf** [comment] 2016-10-09 12:48
I used Promiscuous, UserCSV and Mic Bargraph.
Debug disabled.
Experimental off, so I don't even know about netmon :-)

**Comment by sijskes** [comment] 2016-10-09 12:53
@ik2cnf when you startup, there is a blank screen? even no logo or text message?

**Comment by sijskes** [comment] 2016-10-09 12:58
do you have the commit hash from the working version and the first non-working?

**Comment by ik2cnf** [comment] 2016-10-09 15:52
@sijskes at startup I do see the logo and text msg. From then after home screen is as in picture 1 in my previous message.

I realized the problem this morning when I ugraded from last commit.
I don't remember when I upgraded before.

But I tried 3 builds from http://pd0zry.nl/md380-fw/

Just as @mach327, http://pd0zry.nl/md380-fw/firmware-20161008-130001-b8533dad.bin is the last working, next 2 http://pd0zry.nl/md380-fw/firmware-20161008-160001-6a75f895.bin and http://pd0zry.nl/md380-fw/firmware-S13.020-20161008-170001-dc61c974-buildlog.txt don't.

So last commit hash working should be  b8533dad and first not working 6a75f895

Sorry I can't help you with code, but I'm at your disposable for testing

**Comment by sijskes** [comment] 2016-10-09 16:01
@ik2cnf ok, can you double check your config when you have https://github.com/travisgoodspeed/md380tools/commit/6a75f8950a757e8e54a42366575094425d720f84 ?
this might be a bug in upgrading the config in spiflash.

**Comment by ik2cnf** [comment] 2016-10-09 16:17
@sijskes 
Simon please, what do you mean with "check your config"? Radio configuration?
Sorry but I'm newby to github, and the only way I know to upload an old firmware is by means of md380-dfu and bin in pd0zry repository.
So if you mean other tha radio menu configuration, please be more explicit I'd be glad to try

**Comment by sijskes** [comment] 2016-10-09 16:19
@ik2cnf i meant the settings like 'debug' 'netmon' 'experimental'

**Comment by ik2cnf** [comment] 2016-10-09 16:22
Fine!
now I cannot do a test, but as soon as I can I'll give a try with a plain configuration and report here
Thanks

**Comment by on8vm** [comment] 2016-10-09 17:01
On my side, I have also tried the last firmware that wasn't giving you display problems (20161008-130001-**b8533dad**).
I have always the blank screen issue. Even just after startup (that I see without problems).

In my case **the only enabled feature is users.csv**, all the rest (experimental, promiscuous, devonly) is disabled.

KR,
VM

**Comment by roelandjansen** [comment] 2016-10-09 17:03
also be aware that it is difficult for a start to support the builds other than what we provide in https://github.com/roelandjansen/md380tools/releases

The build that we provide are tested and we do pick stable releases and generally know their issues.

As @sijskes said -- disable debug, netmon, experimental stuff -- those are debugging/ engineering aids that are not expected to work for everyone (and having said that -- when those options are on, you are on your own -- generally we don't take bug reports on that).

Now that this is said -- could you load an official TYT firmware,  and then flash the latest stable release from the link above, with experimental/debug/netmon off? Also re-load the config file (inadvertedly being named "codeplug',  without any changes (!) and edit your DMR ID on the TYT itself. 

We need to have a clean start here, hence this request.

**Comment by mach327** [comment] 2016-10-09 19:46
Unfortunately, my VHF md-380 shows this bug, and I have not enabled Netmon - yet it acts as if I have.
I cannot even enter the menu to turn it off - the radio appears to crash, and reboots.

I will try a clean slate and see where that gets the VHF radio - will report back.

**Comment by ik2cnf** [comment] 2016-10-09 19:53
**Update**
I started from last working firmware b8533da and disabled all features in MD380tools menu.
Then I upgraded to 6a75f89, as requested by Simon.
This time at reboot I had **no** problem. I reintroduced, one by one, Promiscuous Mode, UsersCSV and Mic bargraph, each time rebooting the radio. I tried any possible combinations of the 3 features and I had no problem.
So I made a git pull, make clean and make all flash and now my MD380 is running last commit 4687f7c without troubles.
I do not know what kind of problem occurred, but I should recommend to restart with a tested firmware and a clean config in case of troubles.
I would like to learn what caused this strange behaviour.
Any hint appreciated
Thank you all

**Comment by mach327** [comment] 2016-10-09 20:36
I wrote a clean codeplug from `codeplugs/` to radio.
Then, I did the following procedure twice - once for the [latest stable release](https://github.com/roelandjansen/md380tools/releases/tag/e762fc9) and once for the `6a75f895` firmware.

1. Flash official Tytera firmware. Booted it and confirmed no issues.
2. Flash the new firmware. Booted it and confirmed issue.
3. Flash the last working firmware (well, last working pd0rzy build from above) - ensure netmon, debug, and all other md380tools features are disabled. Issue not present.
4. Flash the new firmware. Issue still exists.

Any firmware past '6a75f895' appears to make my VHF radio crash and reboot when I try to enter DevOnly menu, and presents the display issues described above. The commits before that do not display either issue. 
My old UHF md-380 does not crash, and only has the display issue when Netmon 3 is enabled (that is, a non-issue). This is true of all tested firmwares so far. I include this detail only because it might indicate where the VHF radio is having issues.

**Comment by mach327** [comment] 2016-10-09 20:46
Aha! My VHF model, when flashed, appeared to be turning Netmon3 on by itself. Reading the release notes for https://github.com/roelandjansen/md380tools/releases/tag/e762fc9, they indicated I could turn off Netmon with a long-press of the "7" key. This fixed the display issue for me! And, get this - I can also use the DevOnly menu without it crashing now, including to turn on and off Netmon 3.
Mine and @ik2cnf's issue might just be netmon3 accidentally defaulting to on, or not initializing properly, in some models.

@ik2cnf, give that a shot. Long press "7" after boot, and then try changing the channel to make the screen redraw.

**Comment by sijskes** [comment] 2016-10-10 08:12
@mach327 @ik2cnf i might have borked the compatibility mode of the configuration loading from spi flash. sorry about that. i'm testing an improved up and downgrade compatible configuration storage.

**Comment by ik2cnf** [comment] 2016-10-10 18:44
After @mach327 advice I found I can replicate the blank screen behaviour entering NetMon 3. I can restore to normal through (dirty) menus disabling NetMon.
So I suppose NetMon feature was inadvertently activated (I never did before).
On the contrary neither long-press of  "8", "9" and "#" keys  activated NetMon features nor "7" key disabled it.

**Comment by mach327** [comment] 2016-10-11 01:12
@ik2cnf I don't know why the long press keys don't work, but I would guess they need experimental and/or debug enabled.

At least we have some idea of that particular problem, but it seems @on8vm's issue is not necessarily the same.
If there's any hints as to reproducing the old problem, I'll happily try and test with my radios.

**Comment by roelandjansen** [comment] 2016-10-11 07:06
debug needs to be on for hot key support.

**Comment by ik2cnf** [comment] 2016-10-11 16:33
True, with debug on I got hot keys working.
OT: Pls, where can I find documentation about debug, experimental and devonly features?

**Comment by sijskes** [comment] 2016-10-11 16:35
for experimental debug and devonly. "use the source luke".

**Comment by ik2cnf** [comment] 2016-10-11 16:36
:-)

**Comment by sijskes** [comment] 2016-10-11 16:43
these options are really not stable enough to jusitfy documentation and the work when the meaning of those options change.

for now:
debug: enable dmesg (for now also enable hotkeys)
netmon: allow selection of netmon screen when hotkeys out of action 
experimental: very volatile in function.

hotkeys: 7,8,9,# = normal,nm1,nm2,nm3 
6 = dump syslog to dmesg
5 = clear syslog

**Comment by sijskes** [comment] 2016-11-01 13:23
closing no solution, no progress

**Closed by sijskes** 2016-11-01 13:23 UTC
Labels: hard
