### ISSUE TITLE
Options in MB380tools will not stay enabled

### ISSUE THREAD

**Issue by kb1fx** [travisgoodspeed/md380tools#131] opened 2016-05-22 19:54 UTC
I'm using `MD380Tools Ver : 2016-05-15 firmware in both UHF & VHF MD380.
In the VHF in the MD380 tools options: 
roger beep, Debug, Promiscuous & experimental will not remain enabled. 
I need to enable these every time I turn on the radio.
I only have this issue with experimental not staying enabled with the UHF radio

73's
Mike

**Comment by travisgoodspeed** [comment] 2016-05-22 20:20
This is a duplicate of Issue #66.  Some MD380s have one megabyte of memory, while others have sixteen.  Currently, the menu items aren't saved properly in the 1MB devices because we don't yet know where it's safe to store them.

Closing this issue as a duplicate.

**Closed by travisgoodspeed** 2016-05-22 20:20 UTC
