### ISSUE TITLE
Feature: Talker Alias

### ISSUE THREAD

**Issue by w7xm** [travisgoodspeed/md380tools#681] opened 2017-02-12 02:41 UTC
#163 was closed and would like to see this reopened and actively worked on since Brandmeister is now supporting the Talker Alias along with openSPOT and MMDVM. Hytera is also supporting this with their latest firmware updates. I have a request into Motorola to see when they might support this in their future firmware releases and will report back when they do. But this should not inhibit from having the MD380 now using it since Brandmeister is using it.

**Comment by travisgoodspeed** [comment] 2017-02-14 00:20
We're aware that folks would really like this feature, but for now, no one on the dev team has volunteered to write it.  Pull requests are always welcome, of course.

Closing as a duplicate of issues #163 and #370.

**Comment by zarya** [comment] 2017-02-17 21:00
First working version of Talker alias in netmon
![image](https://cloud.githubusercontent.com/assets/387694/23083075/7076e0f8-f55c-11e6-8abe-92fe46ed3f5d.png)

**Comment by travisgoodspeed** [comment] 2017-02-17 21:02
Reopening issue now that progress is being made.  Thanks, @zarya!

**Comment by lb5je** [comment] 2017-02-20 19:08
Is it only Hytera radios that generate this info. Seems that not all users "send" TA.

73 de LB5JE

**Comment by w7xm** [comment] 2017-02-20 19:47
This is true. Hytera is the only one presently Sending the TA info.
Otherwise it is generated by Brandmeister if no ta is sent.

On Mon, Feb 20, 2017 at 11:08 AM lb5je <notifications@github.com> wrote:

Is it only Hytera radios that generate this info. Seems that not all users
"send" TA.

73 de LB5JE

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/travisgoodspeed/md380tools/issues/681#issuecomment-281159717>,
or mute the thread

**Comment by jruys** [comment] 2017-02-27 13:13
I notice the MD380 displays TA from Brandmeister OK, but does not show TA when receiving directly from a Hytera MD/PD 785. I'm using compressed IP and tried both 7, 8 and 16 bit encoding. 

Is this expected behavior? Hytera seems to send the TA later than Brandmeister does.

**Comment by DL2MF** [comment] 2017-03-17 17:57
Via our local repeater TA from Hytera PD785 is received during first TX ans already shown at the end of the first RX_screen change in my fork. Did you already try this?

**Comment by shawnchain** [comment] 2019-12-26 16:28
Hi,
I would like to know if MD380 could decode the TA info from Brandmeister or not ?

I did have "Talker Alias/TA & UserDB" options in the "Show Calls" menu in MD380 but the screen always displays "No entry in your user.csv" error message instead of the desired TA string.

But another Hytera PD980 works fine for the same RF signal.

Am I missed something ? 

Thanks,

Shawn

**Comment by PD0DIB** [comment] 2019-12-26 19:48
For support:
See / search for theTYT MD380 tools on Facebook...
73 de PD0DIB | Rob

Op do 26 dec. 2019 17:29 schreef Shawn <notifications@github.com>:

**Comment by DL2MF** [comment] 2020-01-06 22:48
Why should someone interested in developer informations visit an F***book group (people aware of data protection might not use it), when developers can be reached and reply here directly?

TA and UserDB are two complete different features:
- talker alias is digital information (name/callsigm/user info) set and transmitted by the user during his DMR transmission
- UserDB is an index file of DMR id's where a lookup is being mad with the DMR id submitted from the repeater and displaying the textinformation from the DB if the ID was found.

**Comment by rogerclarkmelbourne** [comment] 2020-01-07 02:32
@DL2MF  +1

F**book is another form of dark web, with very limited visibility to search engines etc.

**Comment by travisgoodspeed** [comment] 2020-01-07 04:08
I hate Facebook as much as the rest of you, but I really can't handle the noise of feature requests going directly into the Github issue tracker.

Closing as merged in #698.

**Closed by travisgoodspeed** 2020-01-07 04:08 UTC
Labels: wish list

**Comment by shawnchain** [comment] 2020-01-10 06:43
I'm not requesting the feature here, actually I have developed my own reflector server like BM and supports customized TA info. Yes it eats me lots  of time to read the 3 volumes of ETSI spec...
 
But unfortunately I do not have too much time dig into the MD380 code for the decoding issue currently. But I believe there is a bug there.
Anyway, thanks for the feedback.

Cheers,

BG5HHP

**Comment by rogerclarkmelbourne** [comment] 2020-01-10 09:06
@shawnchain 

I presume you've considered using the OpenGD77 for your tests. TA Rx and Tx are now supported
