### ISSUE TITLE
problem Netmon Function

### ISSUE THREAD

**Issue by PD1WP** [travisgoodspeed/md380tools#340] opened 2016-09-21 08:44 UTC
![20160921_102954](https://cloud.githubusercontent.com/assets/16933496/18703700/5f8ca0ec-7fe7-11e6-9ec3-8d7e867583c9.jpg)
![20160921_103042](https://cloud.githubusercontent.com/assets/16933496/18703701/5f90d20c-7fe7-11e6-9d7e-e3fd4b757418.jpg)
![20160921_103110](https://cloud.githubusercontent.com/assets/16933496/18703702/5f92e1c8-7fe7-11e6-9118-1d2ca45f87c1.jpg)

if got a problem with the Netmon funcion in your latest firmware update.
What does this feature because my handheld transceiver no longer work properly if netmon is turned on.
I have a few pictures added. 
Thanks for your support

**Comment by sijskes** [comment] 2016-09-21 09:15
have you tried with netmon: off, debug: off?

**Comment by sijskes** [comment] 2016-09-21 09:30
please try latest version, it is less intrusive when netmon is disabled.

**Comment by PD1WP** [comment] 2016-09-21 09:47
Yes..  I will flash the  latest version of your firmware. Thanks..  Is it possible to get a manual what netmon does? Thank you for your time.

**Comment by sijskes** [comment] 2016-09-21 09:54
it doesn't do much now. it shows some internal variables, channel name, tg name.
it helps a developer to see what is going on in the internals.
you can always look, but you need to understand the source code to make sense of it, and even then, it is still a mystery what most of the internal variables really do.

**Comment by PD1WP** [comment] 2016-09-21 10:15
Okay.. I just flash it and have the latest version.  The pictures shows my screen when I  enable the Netmon  function.  Do I need to enable also the debug mode?  The strange numbers disappears when I turn off the Netmon function. Thanks for taking the time to give me the answer on my questions..  (sorry.. For  English writing)  PD1WP Wilfred from Apeldoorn, 
![20160921_120612](https://cloud.githubusercontent.com/assets/16933496/18707146/0bc6c79a-7ff5-11e6-9c8c-97f207748063.jpg)
![20160921_120636](https://cloud.githubusercontent.com/assets/16933496/18707152/116a6850-7ff5-11e6-8c92-4e75e592cb29.jpg)

 the Netherlands

**Comment by sijskes** [comment] 2016-09-21 10:25
no, you dont need debug mode. set it to disabled.

and yes, the strange numbers are from netmon. they ARE netmon.

netmon is a reference to a special mode that was included in nokia phones. not intended for normal users. it was a whole lot of very complicated numbers. 

if you dont like the strange numbers, disable netmon.

**Comment by travisgoodspeed** [comment] 2016-09-23 20:47
Closing this issue as the expected behavior of Netmon.

Perhaps we should enable the UsersCSV display by default, or segregate things like Netmon to a "developers only" menu, to lessen confusion?

**Closed by travisgoodspeed** 2016-09-23 20:47 UTC

**Comment by sijskes** [comment] 2016-09-23 20:51
i like the developer only menu remark.
