### ISSUE TITLE
Error from Latest commit 7de3fea  

### ISSUE THREAD

**Issue by YV5OF** [travisgoodspeed/md380tools#112] opened 2016-05-11 14:21 UTC
Hi Team,

Now clone git repository and make, during compilation they appeared a series of warning:

```
**First : **
src/dmr.c: In function 'dmr_apply_squelch_hook':
src/dmr.c:131:3: warning: passing argument 2 of 'dmr_apply_squelch' makes integer from pointer without a cast [enabled by default]
   dmr_apply_squelch(firstthing,mode);
   ^
src/dmr.c:131:3: note: expected 'int' but argument is of type 'char *'
src/dmr.c: In function 'dmr_apply_privsquelch_hook':
src/dmr.c:147:3: warning: passing argument 2 of 'dmr_apply_squelch' makes integer from pointer without a cast [enabled by default]
   dmr_apply_squelch(firstthing,mode);
   ^
src/dmr.c:147:3: note: expected 'int' but argument is of type 'char *'


**Second : **

src/md380-2.032.c:11:9: warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]
 #pragma GCC diagnostic ignored "-Wint-conversion"
         ^
src/md380-2.032.c:16:61: warning: initialization makes pointer from integer without a cast [enabled by default]
 int (*md380_spiflash_read)(void *dst, long adr, long len) = 0x0802fd83;
                                                             ^
src/md380-2.032.c:17:62: warning: initialization makes pointer from integer without a cast [enabled by default]
 void (*md380_spiflash_write)(void *dst, long adr, long len) =0x0802fe6b;
                                                              ^
src/md380-2.032.c:19:80: warning: initialization makes pointer from integer without a cast [enabled by default]
 int (*md380_spiflash_security_registers_read)(void *dst, long adr, long len) = 0x080301bd;
                                                                                ^
src/md380-2.032.c:21:35: warning: initialization makes pointer from integer without a cast [enabled by default]
 void (*md380_spiflash_enable)() = 0x0802fe37;
                                   ^
src/md380-2.032.c:22:36: warning: initialization makes pointer from integer without a cast [enabled by default]
 void (*md380_spiflash_disable)() = 0x0802fe53;
                                    ^
src/md380-2.032.c:23:31: warning: initialization makes pointer from integer without a cast [enabled by default]
 void (*md380_spiflash_wait)()=0x0802fe15;
                               ^
src/md380-2.032.c:25:53: warning: initialization makes pointer from integer without a cast [enabled by default]
 void (*md380_spiflash_block_erase64k)(uint32_t adr)=0x0802fbb7;
                                                     ^
src/md380-2.032.c:26:53: warning: initialization makes pointer from integer without a cast [enabled by default]
 void (*md380_spiflash_sektor_erase4k)(uint32_t adr)=0x0802fb83;
                                                     ^
src/md380-2.032.c:28:43: warning: initialization makes pointer from integer without a cast [enabled by default]
 INT8U (*md380_spi_sendrecv)(INT8U data) = 0x0802fdc9; // SPI1
                                           ^
src/md380-2.032.c:36:22: warning: initialization makes pointer from integer without a cast [enabled by default]
        int maxlen) = 0x0800D88B;
                      ^
src/md380-2.032.c:39:23: warning: initialization makes pointer from integer without a cast [enabled by default]
       uint64_t pos) = 0x08022887;
                       ^
src/md380-2.032.c:43:37: warning: initialization makes pointer from integer without a cast [enabled by default]
                      int unknown) = 0x0801cf1d; // max 19 char ???
                                     ^
src/md380-2.032.c:45:73: warning: initialization makes pointer from integer without a cast [enabled by default]
 void (*gfx_chars_to_display)(wchar_t *str, int x, int y, int unknown) = 0x0801cf1d;
                                                                         ^
src/md380-2.032.c:47:34: warning: initialization makes pointer from integer without a cast [enabled by default]
 void (*gfx_select_font)(void *p)=0x8020975;
                                  ^
src/md380-2.032.c:48:37: warning: initialization makes pointer from integer without a cast [enabled by default]
 void (*gfx_set_bg_color)(int color)=0x801c5e1;
                                     ^
src/md380-2.032.c:49:37: warning: initialization makes pointer from integer without a cast [enabled by default]
 void (*gfx_set_fg_color)(int color)=0x801c5e9;
                                     ^
src/md380-2.032.c:51:63: warning: initialization makes pointer from integer without a cast [enabled by default]
 void (*gfx_blockfill)(int xmin, int ymin, int xmax, int ymax)=0x0801cb05;
                                                               ^
src/md380-2.032.c:54:36: warning: initialization makes pointer from integer without a cast [enabled by default]
 void* (*dmr_call_end)(void *pkt) = 0x0803f33d;
                                    ^
src/md380-2.032.c:56:38: warning: initialization makes pointer from integer without a cast [enabled by default]
 void* (*dmr_call_start)(void *pkt) = 0x0803ec87;
                                      ^
src/md380-2.032.c:58:48: warning: initialization makes pointer from integer without a cast [enabled by default]
 void* (*dmr_handle_data)(void *pkt, int len) = 0x0804b66d;
                                                ^
src/md380-2.032.c:60:36: warning: initialization makes pointer from integer without a cast [enabled by default]
 void* (*dmr_sms_arrive)(void *pkt)=0x0803f03d;
                                    ^
src/md380-2.032.c:62:78: warning: initialization makes pointer from integer without a cast [enabled by default]
 void (*dmr_apply_squelch)(char *dmr_squelch_firsthing, int dmr_squelch_mode)=0x080303b5;
                                                                              ^
src/md380-2.032.c:64:29: warning: initialization makes pointer from integer without a cast [enabled by default]
 int (*dmr_before_squelch)()=0x0803ef6d;
                             ^
src/md380-2.032.c:67:26: warning: initialization makes pointer from integer without a cast [enabled by default]
 char* dmr_squelch_mode = 0x2001d35f;
                          ^
src/md380-2.032.c:69:33: warning: initialization makes pointer from integer without a cast [enabled by default]
 char** dmr_squelch_firstthing = 0x2001d118;
                                 ^
src/md380-2.032.c:74:48: warning: initialization makes pointer from integer without a cast [enabled by default]
 int (*usb_upld_handle)(void*, char*, int, int)=0x0808d3d9;
                                                ^
src/md380-2.032.c:76:48: warning: initialization makes pointer from integer without a cast [enabled by default]
 int (*usb_send_packet)(void*, char*, uint16_t)=0x080577af;
                                                ^
src/md380-2.032.c:80:26: warning: initialization makes pointer from integer without a cast [enabled by default]
 int (*usb_dnld_handle)()=0x0808ccbf;//2.032
                          ^
src/md380-2.032.c:88:18: warning: initialization makes pointer from integer without a cast [enabled by default]
 char *welcomebmp=0x080f9ca8;
                  ^
src/md380-2.032.c:92:155: warning: initialization makes pointer from integer without a cast [enabled by default]
 INT8U (*OSTaskCreateExt)(void (*task)(void *pd), void *pdata, OS_STK *ptos, INT8U prio, INT16U id, OS_STK *pbos, INT32U stk_size, void *pext, INT16U opt)=0x804bbf5;
                                                                                                                                                           ^
src/md380-2.032.c:93:63: warning: initialization makes pointer from integer without a cast [enabled by default]
 void* (*OSTaskNameSet)(INT8U prio, INT8U *pname, INT8U *perr)=0x804bcc1;
                                                               ^
src/md380-2.032.c:95:33: warning: initialization makes pointer from integer without a cast [enabled by default]
 int (*OS_ENTER_CRITICAL)()    = 0x08041df9;
                                 ^
src/md380-2.032.c:96:33: warning: initialization makes pointer from integer without a cast [enabled by default]
 void (*OS_EXIT_CRITICAL)(int) = 0x08041e01;
                                 ^
src/md380-2.032.c:99:38: warning: initialization makes pointer from integer without a cast [enabled by default]
 OS_EVENT *(*OSSemCreate)(uint16_t) = 0x803da2c+1;
                                      ^
src/md380-2.032.c:100:42: warning: initialization makes pointer from integer without a cast [enabled by default]
 OS_EVENT  ** OSSemCreate_hook0_event_mem=0x2001d124;
                                          ^
src/md380-2.032.c:101:42: warning: initialization makes pointer from integer without a cast [enabled by default]
 OS_EVENT  ** OSSemCreate_hook1_event_mem=0x2001d128;
                                          ^
src/md380-2.032.c:103:71: warning: initialization makes pointer from integer without a cast [enabled by default]
 void (*OSSemPend)(OS_EVENT *pevent, uint32_t timeout,  uint8_t *perr)=0x803da78+1;
                                                                       ^
src/md380-2.032.c:104:40: warning: initialization makes pointer from integer without a cast [enabled by default]
 uint8_t (*OSSemPost)(OS_EVENT *pevent)=0x803db68+1;
                                        ^
src/md380-2.032.c:106:59: warning: initialization makes pointer from integer without a cast [enabled by default]
 uint8_t (*md380_OSMboxPost)(OS_EVENT *pevent, void *pmsg)=0x080303b4+1;
                                                           ^
src/md380-2.032.c:109:32: warning: initialization makes pointer from integer without a cast [enabled by default]
 void     *(*main_menu)(void *)=0x08039c23;
                                ^
src/md380-2.032.c:110:49: warning: initialization makes pointer from integer without a cast [enabled by default]
 void     *(*md380_create_main_meny_entry)(void)=0x0800c189;
                                                 ^
src/md380-2.032.c:111:49: warning: initialization makes pointer from integer without a cast [enabled by default]
 void     *(*md380_menu_numerical_input)(void) = 0x801a2d6;
                                                 ^
src/md380-2.032.c:112:95: warning: initialization makes pointer from integer without a cast [enabled by default]
 void     *(*md380_create_menu_entry)(int a, void *b , void *c, void  *d, int e, int f ,int g)=0x0800c731;
                                                                                               ^
src/md380-2.032.c:113:42: warning: initialization makes pointer from integer without a cast [enabled by default]
 void     *(*md380_menu_entry_back)(void)=0x800f452;
                                          ^
src/md380-2.032.c:114:50: warning: initialization makes pointer from integer without a cast [enabled by default]
 void     *(*md380_menu_entry_programradio)(void)=0x80127d0;
                                                  ^
src/md380-2.032.c:116:35: warning: initialization makes pointer from integer without a cast [enabled by default]
 uint32_t *md380_menu_0x20001114 = 0x20001114;
                                   ^
src/md380-2.032.c:117:35: warning: initialization makes pointer from integer without a cast [enabled by default]
 uint8_t  *md380_menu_0x200011e4 = 0x200011e4;
                                   ^
src/md380-2.032.c:118:35: warning: initialization makes pointer from integer without a cast [enabled by default]
 uint8_t  *md380_menu_0x2001d3c1 = 0x2001d3c1;
                                   ^
src/md380-2.032.c:119:35: warning: initialization makes pointer from integer without a cast [enabled by default]
 uint8_t  *md380_menu_0x2001d3ed = 0x2001d3ed;
                                   ^
src/md380-2.032.c:120:35: warning: initialization makes pointer from integer without a cast [enabled by default]
 uint8_t  *md380_menu_0x2001d3ee = 0x2001d3ee;
                                   ^
src/md380-2.032.c:121:35: warning: initialization makes pointer from integer without a cast [enabled by default]
 uint8_t  *md380_menu_0x2001d3ef = 0x2001d3ef;
                                   ^
src/md380-2.032.c:122:35: warning: initialization makes pointer from integer without a cast [enabled by default]
 uint8_t  *md380_menu_0x2001d3f0 = 0x2001d3f0;
                                   ^
src/md380-2.032.c:123:35: warning: initialization makes pointer from integer without a cast [enabled by default]
 uint8_t  *md380_menu_0x2001d3f1 = 0x2001d3f1;
                                   ^
src/md380-2.032.c:124:35: warning: initialization makes pointer from integer without a cast [enabled by default]
 uint8_t  *md380_menu_0x2001d3f4 = 0x2001d3f4;
                                   ^
src/md380-2.032.c:125:30: warning: initialization makes pointer from integer without a cast [enabled by default]
 uint8_t  *md380_menu_depth = 0x200011e4;
                              ^
src/md380-2.032.c:126:33: warning: initialization makes pointer from integer without a cast [enabled by default]
 wchar_t  *md380_menu_edit_buf = 0x2001b716;
                                 ^
src/md380-2.032.c:127:39: warning: initialization makes pointer from integer without a cast [enabled by default]
 uint8_t  *md380_menu_entry_selected = 0x2001d3b2;
                                       ^
src/md380-2.032.c:128:27: warning: initialization makes pointer from integer without a cast [enabled by default]
 uint8_t  *md380_menu_id = 0x2001d3c2;
                           ^
src/md380-2.032.c:129:33: warning: initialization makes pointer from integer without a cast [enabled by default]
 void     *md380_menu_mem_base = 0x20019df0;
                                 ^
src/md380-2.032.c:130:31: warning: initialization makes pointer from integer without a cast [enabled by default]
 void     *md380_menu_memory = 0x2001c148;
                               ^
src/md380-2.032.c:132:35: warning: initialization makes pointer from integer without a cast [enabled by default]
 uint8_t  *md380_wt_programradio = 0x080d175c;
                                   ^
src/md380-2.032.c:135:18: warning: initialization makes pointer from integer without a cast [enabled by default]
 char* channelnum=0x2001d376;
                  ^
src/md380-2.032.c:136:30: warning: initialization makes pointer from integer without a cast [enabled by default]
 int (*read_channel_switch)()=0x0804d269;
                              ^
src/md380-2.032.c:141:47: warning: initialization makes pointer from integer without a cast [enabled by default]
 void (*c5000_spi0_readreg)(int reg, char*buf)=0x0803e2f5;
                                               ^
src/md380-2.032.c:142:47: warning: initialization makes pointer from integer without a cast [enabled by default]
 void (*c5000_spi0_writereg)(int reg, int val)=0x0803e2a9;
                                               ^
src/md380-2.032.c:145:32: warning: initialization makes pointer from integer without a cast [enabled by default]
 char* (*aes_cipher)(char *pkt)=0x080356b1;
                                ^
src/md380-2.032.c:149:43: warning: initialization makes pointer from integer without a cast [enabled by default]
     short a5, short a6, short a7, int a8)=0x08050d91;
                                           ^
src/md380-2.032.c:151:57: warning: initialization makes pointer from integer without a cast [enabled by default]
 int (*ambe_unpack)(int a1, int a2, char length, int a4)=0x08048c9d;
                                                         ^
src/md380-2.032.c:155:46: warning: initialization makes pointer from integer without a cast [enabled by default]
          int a4, short a5, short a6, int a7)=0x08051249;
                                              ^
src/md380-2.032.c:159:31: warning: initialization makes pointer from integer without a cast [enabled by default]
 uint32_t *beep_process_unkown=0x2001d178;
                               ^
src/md380-2.032.c:163:42: warning: initialization makes pointer from integer without a cast [enabled by default]
 void (*md380_itow)(wchar_t *, int value)=0x080172ed;
                                          ^
src/md380-2.032.c:164:81: warning: initialization makes pointer from integer without a cast [enabled by default]
 void (*md380_RTC_GetDate)(uint32_t RTC_Format, RTC_DateTypeDef *RTC_DateStruct)=0x08026461;
                                                                                 ^
src/md380-2.032.c:165:81: warning: initialization makes pointer from integer without a cast [enabled by default]
 void (*md380_RTC_GetTime)(uint32_t RTC_Format, RTC_TimeTypeDef* RTC_TimeStruct)=0x0802634b;
                                                                                 ^
src/md380-2.032.c:167:24: warning: initialization makes pointer from integer without a cast [enabled by default]
 uint32_t *md380_dmr_id=0x2001c65c;
                        ^
src/md380-2.032.c:171:24: warning: initialization makes pointer from integer without a cast [enabled by default]
 void (*md380_f_4137)()=0x080290c8+1;
                        ^
src/md380-2.032.c:172:24: warning: initialization makes pointer from integer without a cast [enabled by default]
 void (*md380_f_4520)()=0x08027ae8+1;
                        ^
src/md380-2.032.c:173:24: warning: initialization makes pointer from integer without a cast [enabled by default]
 void (*md380_f_4098)()=0x0804c1d0+1;
                        ^
src/md380-2.032.c:174:24: warning: initialization makes pointer from integer without a cast [enabled by default]
 void (*md380_f_4102)()=0x0804c2aa+1;
                        ^
src/md380-2.032.c:176:37: warning: initialization makes pointer from integer without a cast [enabled by default]
 uint8_t *md380_f_4225_operatingmode=0x2001d3f7;
                                     ^



and the build process at the end does not generate all files.




Then try a **git pull **on the repositories that already had operational, and gender process the following error:

From https://github.com/travisgoodspeed/md380tools
   3b76f31..7de3fea  master     -> origin/master
Updating 3b76f31..7de3fea
error: Your local changes to the following files would be overwritten by merge:
	db/users.csv
Please, commit your changes or stash them before you can merge.
Aborting
```

73!

**Comment by travisgoodspeed** [comment] 2016-05-11 14:41
Most of those warnings are caused by your compiler being a bit old.  They'll go away if you upgrade to arm-none-eabi-gcc-5.2.1, which added support for ignoring the pointer initialization warnings.

The git error is caused by your having local files with changes.  Run `git checkout db` to revert your local changes to the contact database, then `git pull` to update your code.


Please use the Google Group https://groups.google.com/forum/#!forum/md380tools or the IRC channel (#md380 on Freenode) for general support and save the Github issue tracker for bugs and (important) feature requests.  Closing this ticket.

**Closed by travisgoodspeed** 2016-05-11 14:41 UTC
