### ISSUE TITLE
[FEATURE] Vocalization

### ISSUE THREAD

**Issue by paulomartinspt** [travisgoodspeed/md380tools#670] opened 2017-01-24 16:45 UTC
Throw at Ye Grande Ol' Wish List for Christmas

A friend asked me to post this here.
It would be great for nonvisual to have vocalization of the menu options, like it happens with some radios options/channels. I know we have limited memory and functionalities but we never thought the MD380/390 would do all the things you guys make them do nowadays... 👍 
Something for you guys to think about.
Thanks for the attention.

**Comment by travisgoodspeed** [comment] 2017-01-24 17:53
Closing as a duplicate of #580.

We'd love to help visually impaired hams, but for now, it's probably best that they use a radio which already has audio vocalization, such as the Tytera MD280.

73 from Pizza Rat City,
--Travis KK4VCZ

**Closed by travisgoodspeed** 2017-01-24 17:53 UTC

**Comment by paulomartinspt** [comment] 2017-01-26 11:05
Sorry for the duplicate Travis...
Thanks for the reply
