### ISSUE TITLE
flash ID

### ISSUE THREAD

**Issue by autodiag** [travisgoodspeed/md380tools#713] opened 2017-03-04 18:20 UTC
please add to spi id C8 40 18 in fw

**Comment by travisgoodspeed** [comment] 2017-03-04 18:49
Closing as a duplicate of #696.

Feature requests and support requests go to the IRC channel or to the mailing list.  Please?

**Closed by travisgoodspeed** 2017-03-04 18:49 UTC

**Comment by autodiag** [comment] 2017-03-04 19:05
no ansfer IRc and no ansfer mailing list
why dont ansfer and close ??  or what problem this issue ???
