### ISSUE TITLE
Font Replacement Fails in Windows Builds (CRLF bug)

### ISSUE THREAD

**Issue by IZ4FXC** [travisgoodspeed/md380tools#710] opened 2017-03-01 15:25 UTC
Hi everybody!
I've just upgraded my 380 with Git and everything goes perfectly but the fonts.
I can't get the latin font and the radio works (well) with the ugly old one.
I've tried with "make clean flash" and "make clean all", the patches are present in the directories "3.020" and  "d13.020" and in this late i see the .img files with current date.
Where am I wrong?
Thanks for your attention, IZ4FXC Greg.

**Comment by travisgoodspeed** [comment] 2017-03-02 00:48
Please post a screenshot of the font that you find, to help us reproduce the problem.

**Comment by IZ4FXC** [comment] 2017-03-02 07:39
Here is the pic, thank you!
    Gregorio De Michele
Assistenza informatica AUSL Modena
V.le Martiri 56
41026 Pavullo N.F. (MO)
tel. 0536 29247
cell. 320 2260953
Orari ufficio.

    Il 02/03/2017 01:48, Travis Goodspeed
      ha scritto:
    
    
      Please post a screenshot of the font that you find, to help us
        reproduce the problem.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/travisgoodspeed/md380tools","title":"travisgoodspeed/md380tools","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/travisgoodspeed/md380tools"}},"updates":{"snippets":[{"icon":"PERSON","message":"@travisgoodspeed in #710: Please post a screenshot of the font that you find, to help us reproduce the problem."}],"action":{"name":"View Issue","url":"https://github.com/travisgoodspeed/md380tools/issues/710#issuecomment-283520394"}}}

**Comment by Wolf-DL4YHF** [comment] 2017-03-02 17:39
Looks the same here (with the ugly monsterous serifes) but I never paid much attention to it. 
Could this be related with the building process / host system (I usually build under windoze / MinGW32..), something missing or simply not invoked by the makefile or scripts ?

**Comment by DL2MF** [comment] 2017-03-04 22:06
The font's are patched to the merged img very close to the end of the build process. If fonts successfully being replaced, it should look like this:

`Patching hword at 0809bf0a to 483c
Patching hword at 0809bf0c to 4700
Patching word at 0809bffc to 080fa105
../../md380-gfx --firmware=patched.img --gfx=replacement-font-big-latin.pbm fontreplace
DEBUG: reading "patched.img"
DEBUG: writing "patched.img"
../../md380-gfx --firmware=patched.img --gfx=replacement-font-small-latin.pbm fontreplace
DEBUG: reading "patched.img"
DEBUG: writing "patched.img"
make[2]: Verzeichnis „/home/mg/md380tools/patches/s13.020“ wird verlassen
cp ../patches/s13.020/patched.img ./merged.img
python2 merge_s13.020.py merged.img applet.img 0x809c000
Merging an applet.
Loading symbols from applet.img.sym
`

**Comment by travisgoodspeed** [comment] 2017-03-04 22:14
@Wolf-DL4YHF In your Windows build process, is md380-gfx working properly?  Could you please try it alone to see if fontreplace is working?

**Comment by Wolf-DL4YHF** [comment] 2017-03-04 23:09
This is what I get from the console (MinGW32) when invoking it manually:

Wolf@YHF6 /c/tools/md380tools
$ python md380_gfx.py --firmware=patches/d13.020/patched.img 
--gfx=patches/d13.020/replacement-font-big-latin.pbm fontreplace
DEBUG: reading "patches/d13.020/patched.img"

Wolf@YHF6 /c/tools/md380tools
$

No error message. The same DEBUG output also when running it from the 
makefile.
Should I run the Python script in a debugger to see what's going on ?



Am 04.03.2017 um 23:14 schrieb Travis Goodspeed:

**Comment by travisgoodspeed** [comment] 2017-03-04 23:11
Maybe take a look at the file itself, to see if the script is changing anything at all?

**Comment by Wolf-DL4YHF** [comment] 2017-03-04 23:46
Looks like the old "\n" vs "\r\n" issue again.
In...

def pbmparse(pbml):
     """Convert PBM(P1) ascii bitmap image to glyph object""" while (pbml != [])and (pbml[0] !='P1'):
         pbml = pbml[1:]


... it never sees 'P1' but 'P1\r' because the split('\n') didn't remove 
that character. Should be easy to fix when converting the file from a 
long string into single lines.
Am 05.03.2017 um 00:11 schrieb Travis Goodspeed:

**Comment by Wolf-DL4YHF** [comment] 2017-03-05 00:54
Simply replacing
    something.split('\n')
by
   something.splitlines()
did the trick. Nice clean fonts when building the firmware now under 
windows, too.

73+gn
    Wolf .

Am 05.03.2017 um 00:11 schrieb Travis Goodspeed:

**Comment by travisgoodspeed** [comment] 2017-03-05 04:23
Thanks a million for hunting down the cause of this bug.  I'll merge a quick patch in the morning (US/Eastern time) and close this issue after you confirm the fix works on Windows.

Feel free to do a pull request if you wake up first.

73 from Philly,
-Travis

**Comment by Wolf-DL4YHF** [comment] 2017-03-05 08:20
Is there an easy way for a "single-file PR" without having to create a new branch (different repo where I have write access), or to pull a request for a "single file" in an existing repo (mine) without pulling all the others in my branch ? Or simply attach that single file here ?

Anyway, since I'm lazy and not really familiar with github, the modified file is here (good old FTP, took a few milliseconds to upload instead of clicking around for an hour in the web GUI):   
http://www.qsl.net/dl4yhf/RT3/md380_gfx.py

**Comment by IZ4FXC** [comment] 2017-03-05 16:19
Actually out for job, I'll try it too on monday morning. (UTC)
Thank you guys!

**Comment by travisgoodspeed** [comment] 2017-03-05 16:22
@Wolf-DL4YHF From the command-line, you can push as many branches to your own fork.  The general idea is that you give each branch a different name, one per feature, and then do pull requests from them separately.

I'm pushing the fix to the master branch in just a moment.

73 from Philly,
--Travis

**Closed** 2017-03-05 16:22 UTC
Labels: bug (md380tools), easy, Windows
