### ISSUE TITLE
Menu-Items in md380tools depending on TRX-version?

### ISSUE THREAD

**Issue by dg9vh** [travisgoodspeed/md380tools#128] opened 2016-05-18 13:41 UTC
Corresponding to https://github.com/travisgoodspeed/md380tools/issues/117 could it be possible to disable menu-items on VHF-Versions when they are not working there?

Don't know if one could detect within the firmware what version TRX is but I think writing a value into addl_config and reading it out and if it is not the same could be a good hint of being on a VHF, right?

**Comment by travisgoodspeed** [comment] 2016-05-18 13:47
This is a duplicate of issue #66.  As discussed in that issue, this will be fixed by finding a VHF friendly location for our settings structure. 

Closing as a duplicate.

**Closed by travisgoodspeed** 2016-05-18 13:47 UTC
