### ISSUE TITLE
Latest Firmware makes my MD380 does not start.

### ISSUE THREAD

**Issue by PD1LOI** [travisgoodspeed/md380tools#290] opened 2016-09-14 08:04 UTC
Latest Firmware makes my MD380 does not start. just a blank white screen is what you see.
Firmware 973K big works.
Firmware 1000 K big does not work.

**Comment by travisgoodspeed** [comment] 2016-09-14 08:13
We really, *really* need more information with bug reports.  Otherwise we can't reproduce your problem, and that's frustrating for both of us.

I've just verified that both 'make flash' and 'make flash_d02.032` correctly flash functional firmware into a non-GPS MD380.  It is a known issue, tracked by #181, that `make flash_s13.020` only boots on devices with GPS hardware.

We don't have a firmware that is 1000 kilobytes in size.  Could you please provide us with more details of your versions and how you are trying to compile?

73 from Varaždin,
6A/KK4VCZ

**Comment by PD1LOI** [comment] 2016-09-14 08:36
make -C lib clean make[1]: Entering directory
'/home/zarya/md380tools/applet/lib' rm -f misc.o stm32f4xx_dma.o
stm32f4xx_rcc.o stm32f4xx_adc.o stm32f4xx_exti.o stm32f4xx_rng.o
stm32f4xx_can.o stm32f4xx_flash.o stm32f4xx_rtc.o stm32f4xx_crc.o
stm32f4xx_fsmc.o stm32f4xx_sdio.o stm32f4xx_cryp_aes.o stm32f4xx_gpio.o
stm32f4xx_spi.o stm32f4xx_cryp.o stm32f4xx_hash.o stm32f4xx_syscfg.o
stm32f4xx_cryp_des.o stm32f4xx_hash_md5.o stm32f4xx_tim.o
stm32f4xx_cryp_tdes.o stm32f4xx_hash_sha1.o stm32f4xx_usart.o
stm32f4xx_dac.o stm32f4xx_i2c.o stm32f4xx_wwdg.o stm32f4xx_dbgmcu.o
stm32f4xx_iwdg.o stm32f4xx_dcmi.o stm32f4xx_pwr.o libstm32f4.a make[1]:
Leaving directory '/home/zarya/md380tools/applet/lib' rm -f *.img *.lst
*.bin *.elf *.hex *.o *~ *.sym src/*~ src/version.h echo "#define
VERSIONDATE L\"`date "+%Y-%m-%d"`\"" >src/version.h make -C lib make[1]:
Entering directory '/home/zarya/md380tools/applet/lib' arm-none-eabi-gcc -g
-O2 -Wall -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork
-mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc
-Iinc/core -Iinc/peripherals -fshort-wchar -c -o misc.o
src/peripherals/misc.c arm-none-eabi-gcc -g -O2 -Wall -mlittle-endian
-mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_dma.o
src/peripherals/stm32f4xx_dma.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_rcc.o
src/peripherals/stm32f4xx_rcc.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_adc.o
src/peripherals/stm32f4xx_adc.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_exti.o
src/peripherals/stm32f4xx_exti.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_rng.o
src/peripherals/stm32f4xx_rng.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_can.o
src/peripherals/stm32f4xx_can.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_flash.o
src/peripherals/stm32f4xx_flash.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_rtc.o
src/peripherals/stm32f4xx_rtc.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_crc.o
src/peripherals/stm32f4xx_crc.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_fsmc.o
src/peripherals/stm32f4xx_fsmc.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_sdio.o
src/peripherals/stm32f4xx_sdio.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_cryp_aes.o
src/peripherals/stm32f4xx_cryp_aes.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_gpio.o
src/peripherals/stm32f4xx_gpio.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_spi.o
src/peripherals/stm32f4xx_spi.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_cryp.o
src/peripherals/stm32f4xx_cryp.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_hash.o
src/peripherals/stm32f4xx_hash.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_syscfg.o
src/peripherals/stm32f4xx_syscfg.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_cryp_des.o
src/peripherals/stm32f4xx_cryp_des.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_hash_md5.o
src/peripherals/stm32f4xx_hash_md5.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_tim.o
src/peripherals/stm32f4xx_tim.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_cryp_tdes.o
src/peripherals/stm32f4xx_cryp_tdes.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_hash_sha1.o
src/peripherals/stm32f4xx_hash_sha1.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_usart.o
src/peripherals/stm32f4xx_usart.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_dac.o
src/peripherals/stm32f4xx_dac.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_i2c.o
src/peripherals/stm32f4xx_i2c.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_wwdg.o
src/peripherals/stm32f4xx_wwdg.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_dbgmcu.o
src/peripherals/stm32f4xx_dbgmcu.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_iwdg.o
src/peripherals/stm32f4xx_iwdg.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_dcmi.o
src/peripherals/stm32f4xx_dcmi.c arm-none-eabi-gcc -g -O2 -Wall
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -ffreestanding -nostdlib -Iinc -Iinc/core
-Iinc/peripherals -fshort-wchar -c -o stm32f4xx_pwr.o
src/peripherals/stm32f4xx_pwr.c arm-none-eabi-ar -r libstm32f4.a misc.o
stm32f4xx_dma.o stm32f4xx_rcc.o stm32f4xx_adc.o stm32f4xx_exti.o
stm32f4xx_rng.o stm32f4xx_can.o stm32f4xx_flash.o stm32f4xx_rtc.o
stm32f4xx_crc.o stm32f4xx_fsmc.o stm32f4xx_sdio.o stm32f4xx_cryp_aes.o
stm32f4xx_gpio.o stm32f4xx_spi.o stm32f4xx_cryp.o stm32f4xx_hash.o
stm32f4xx_syscfg.o stm32f4xx_cryp_des.o stm32f4xx_hash_md5.o
stm32f4xx_tim.o stm32f4xx_cryp_tdes.o stm32f4xx_hash_sha1.o
stm32f4xx_usart.o stm32f4xx_dac.o stm32f4xx_i2c.o stm32f4xx_wwdg.o
stm32f4xx_dbgmcu.o stm32f4xx_iwdg.o stm32f4xx_dcmi.o stm32f4xx_pwr.o
arm-none-eabi-ar: creating libstm32f4.a make[1]: Leaving directory
'/home/zarya/md380tools/applet/lib' arm-none-eabi-gcc -std=gnu99 -g -O2
-Wall -Tapplet_s13.020.ld -mlittle-endian -mthumb -mcpu=cortex-m4
-mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -fshort-wchar
-DGIT_VERSION=\"a4523e-dirty\" -Wa,-a=main.lst -Iinc -Ilib -Ilib/inc -I.
-Ilib/inc/core -Ilib/inc/peripherals -D "MD380_s13_020" -c -o main.o
src/main.c arm-none-eabi-gcc -std=gnu99 -g -O2 -Wall -Tapplet_s13.020.ld
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -fshort-wchar -DGIT_VERSION=\"a4523e-dirty\"
-Wa,-a=printf.lst -Iinc -Ilib -Ilib/inc -I. -Ilib/inc/core
-Ilib/inc/peripherals -D "MD380_s13_020" -c -o printf.o src/printf.c
arm-none-eabi-gcc -std=gnu99 -g -O2 -Wall -Tapplet_s13.020.ld
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -fshort-wchar -DGIT_VERSION=\"a4523e-dirty\"
-Wa,-a=dmesg.lst -Iinc -Ilib -Ilib/inc -I. -Ilib/inc/core
-Ilib/inc/peripherals -D "MD380_s13_020" -c -o dmesg.o src/dmesg.c
arm-none-eabi-gcc -std=gnu99 -g -O2 -Wall -Tapplet_s13.020.ld
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -fshort-wchar -DGIT_VERSION=\"a4523e-dirty\"
-Wa,-a=usb.lst -Iinc -Ilib -Ilib/inc -I. -Ilib/inc/core
-Ilib/inc/peripherals -D "MD380_s13_020" -c -o usb.o src/usb.c
arm-none-eabi-gcc -std=gnu99 -g -O2 -Wall -Tapplet_s13.020.ld
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -fshort-wchar -DGIT_VERSION=\"a4523e-dirty\"
-Wa,-a=gfx.lst -Iinc -Ilib -Ilib/inc -I. -Ilib/inc/core
-Ilib/inc/peripherals -D "MD380_s13_020" -c -o gfx.o src/gfx.c
arm-none-eabi-gcc -std=gnu99 -g -O2 -Wall -Tapplet_s13.020.ld
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -fshort-wchar -DGIT_VERSION=\"a4523e-dirty\"
-Wa,-a=stm32f4xx_it.lst -Iinc -Ilib -Ilib/inc -I. -Ilib/inc/core
-Ilib/inc/peripherals -D "MD380_s13_020" -c -o stm32f4xx_it.o
src/stm32f4xx_it.c arm-none-eabi-gcc -std=gnu99 -g -O2 -Wall
-Tapplet_s13.020.ld -mlittle-endian -mthumb -mcpu=cortex-m4
-mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -fshort-wchar
-DGIT_VERSION=\"a4523e-dirty\" -Wa,-a=system_stm32f4xx.lst -Iinc -Ilib
-Ilib/inc -I. -Ilib/inc/core -Ilib/inc/peripherals -D "MD380_s13_020" -c -o
system_stm32f4xx.o src/system_stm32f4xx.c arm-none-eabi-gcc -std=gnu99 -g
-O2 -Wall -Tapplet_s13.020.ld -mlittle-endian -mthumb -mcpu=cortex-m4
-mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -fshort-wchar
-DGIT_VERSION=\"a4523e-dirty\" -Wa,-a=addl_config.lst -Iinc -Ilib -Ilib/inc
-I. -Ilib/inc/core -Ilib/inc/peripherals -D "MD380_s13_020" -c -o
addl_config.o src/addl_config.c arm-none-eabi-gcc -std=gnu99 -g -O2 -Wall
-Tapplet_s13.020.ld -mlittle-endian -mthumb -mcpu=cortex-m4
-mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -fshort-wchar
-DGIT_VERSION=\"a4523e-dirty\" -Wa,-a=spiflash.lst -Iinc -Ilib -Ilib/inc
-I. -Ilib/inc/core -Ilib/inc/peripherals -D "MD380_s13_020" -c -o
spiflash.o src/spiflash.c arm-none-eabi-gcc -std=gnu99 -g -O2 -Wall
-Tapplet_s13.020.ld -mlittle-endian -mthumb -mcpu=cortex-m4
-mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -fshort-wchar
-DGIT_VERSION=\"a4523e-dirty\" -Wa,-a=menu.lst -Iinc -Ilib -Ilib/inc -I.
-Ilib/inc/core -Ilib/inc/peripherals -D "MD380_s13_020" -c -o menu.o
src/menu.c arm-none-eabi-gcc -std=gnu99 -g -O2 -Wall -Tapplet_s13.020.ld
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -fshort-wchar -DGIT_VERSION=\"a4523e-dirty\"
-Wa,-a=rtc_timer.lst -Iinc -Ilib -Ilib/inc -I. -Ilib/inc/core
-Ilib/inc/peripherals -D "MD380_s13_020" -c -o rtc_timer.o src/rtc_timer.c
arm-none-eabi-gcc -std=gnu99 -g -O2 -Wall -Tapplet_s13.020.ld
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -fshort-wchar -DGIT_VERSION=\"a4523e-dirty\"
-Wa,-a=beep_process.lst -Iinc -Ilib -Ilib/inc -I. -Ilib/inc/core
-Ilib/inc/peripherals -D "MD380_s13_020" -c -o beep_process.o
src/beep_process.c arm-none-eabi-gcc -std=gnu99 -g -O2 -Wall
-Tapplet_s13.020.ld -mlittle-endian -mthumb -mcpu=cortex-m4
-mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -fshort-wchar
-DGIT_VERSION=\"a4523e-dirty\" -Wa,-a=usersdb.lst -Iinc -Ilib -Ilib/inc -I.
-Ilib/inc/core -Ilib/inc/peripherals -D "MD380_s13_020" -c -o usersdb.o
src/usersdb.c arm-none-eabi-gcc -std=gnu99 -g -O2 -Wall -Tapplet_s13.020.ld
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -fshort-wchar -DGIT_VERSION=\"a4523e-dirty\"
-Wa,-a=os.lst -Iinc -Ilib -Ilib/inc -I. -Ilib/inc/core
-Ilib/inc/peripherals -D "MD380_s13_020" -c -o os.o src/os.c
arm-none-eabi-gcc -std=gnu99 -g -O2 -Wall -Tapplet_s13.020.ld
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -fshort-wchar -DGIT_VERSION=\"a4523e-dirty\"
-Wa,-a=aes.lst -Iinc -Ilib -Ilib/inc -I. -Ilib/inc/core
-Ilib/inc/peripherals -D "MD380_s13_020" -c -o aes.o src/aes.c
arm-none-eabi-gcc -std=gnu99 -g -O2 -Wall -Tapplet_s13.020.ld
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -fshort-wchar -DGIT_VERSION=\"a4523e-dirty\"
-Wa,-a=ambe.lst -Iinc -Ilib -Ilib/inc -I. -Ilib/inc/core
-Ilib/inc/peripherals -D "MD380_s13_020" -c -o ambe.o src/ambe.c
arm-none-eabi-gcc -std=gnu99 -g -O2 -Wall -Tapplet_s13.020.ld
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -fshort-wchar -DGIT_VERSION=\"a4523e-dirty\"
-Wa,-a=dmr.lst -Iinc -Ilib -Ilib/inc -I. -Ilib/inc/core
-Ilib/inc/peripherals -D "MD380_s13_020" -c -o dmr.o src/dmr.c
arm-none-eabi-gcc -std=gnu99 -g -O2 -Wall -Tapplet_s13.020.ld
-mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard
-mfpu=fpv4-sp-d16 -fshort-wchar -DGIT_VERSION=\"a4523e-dirty\"
-Wa,-a=main.elf -Iinc -Ilib -Ilib/inc -I. -Ilib/inc/core
-Ilib/inc/peripherals -D "MD380_s13_020" main.o printf.o dmesg.o usb.o
gfx.o stm32f4xx_it.o system_stm32f4xx.o addl_config.o spiflash.o menu.o
rtc_timer.o beep_process.o usersdb.o os.o aes.o ambe.o dmr.o
lib/startup_stm32f4xx.s -o main.elf -Llib -lstm32f4 -Xlinker
--just-symbols=src/symbols_s13.020
/usr/lib/gcc/arm-none-eabi/4.9/../../../arm-none-eabi/bin/ld: warning:
main.o uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of
wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9/../../../arm-none-eabi/bin/ld: warning:
printf.o uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use
of wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9/../../../arm-none-eabi/bin/ld: warning:
dmesg.o uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of
wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9/../../../arm-none-eabi/bin/ld: warning:
usb.o uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of
wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9/../../../arm-none-eabi/bin/ld: warning:
gfx.o uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of
wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9/../../../arm-none-eabi/bin/ld: warning:
stm32f4xx_it.o uses 2-byte wchar_t yet the output is to use 4-byte wchar_t;
use of wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9/../../../arm-none-eabi/bin/ld: warning:
system_stm32f4xx.o uses 2-byte wchar_t yet the output is to use 4-byte
wchar_t; use of wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9/../../../arm-none-eabi/bin/ld: warning:
addl_config.o uses 2-byte wchar_t yet the output is to use 4-byte wchar_t;
use of wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9/../../../arm-none-eabi/bin/ld: warning:
spiflash.o uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use
of wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9/../../../arm-none-eabi/bin/ld: warning:
menu.o uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of
wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9/../../../arm-none-eabi/bin/ld: warning:
rtc_timer.o uses 2-byte wchar_t yet the output is to use 4-byte wchar_t;
use of wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9/../../../arm-none-eabi/bin/ld: warning:
beep_process.o uses 2-byte wchar_t yet the output is to use 4-byte wchar_t;
use of wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9/../../../arm-none-eabi/bin/ld: warning:
usersdb.o uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use
of wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9/../../../arm-none-eabi/bin/ld: warning: os.o
uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of wchar_t
values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9/../../../arm-none-eabi/bin/ld: warning:
aes.o uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of
wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9/../../../arm-none-eabi/bin/ld: warning:
ambe.o uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of
wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9/../../../arm-none-eabi/bin/ld: warning:
dmr.o uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of
wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9/../../../arm-none-eabi/bin/ld: warning:
lib/libstm32f4.a(stm32f4xx_gpio.o) uses 2-byte wchar_t yet the output is to
use 4-byte wchar_t; use of wchar_t values across objects may fail
/usr/lib/gcc/arm-none-eabi/4.9/../../../arm-none-eabi/bin/ld: warning:
lib/libstm32f4.a(stm32f4xx_rcc.o) uses 2-byte wchar_t yet the output is to
use 4-byte wchar_t; use of wchar_t values across objects may fail
arm-none-eabi-objcopy -O binary main.elf main.img arm-none-eabi-objdump -t
main.elf >main.img.sym cd ../patches/s13.020 && make all make[1]: Entering
directory '/home/zarya/md380tools/patches/s13.020' make[1]: Nothing to be
done for 'all'. make[1]: Leaving directory
'/home/zarya/md380tools/patches/s13.020' cp ../patches/s13.020/patched.img
./experiment.img # use a fresh experiment.img cd ../patches/s13.020 && make
all make[1]: Entering directory '/home/zarya/md380tools/patches/s13.020'
make[1]: Nothing to be done for 'all'. make[1]: Leaving directory
'/home/zarya/md380tools/patches/s13.020' cp ../patches/s13.020/patched.img
./experiment.img python2 merge_s13.020.py experiment.img main.img 0x809c000
Merging an applet. Loading symbols from main.img.sym Merging main.img into
experiment.img at 0809c000 ../md380-fw --wrap experiment.img experiment.bin
DEBUG: reading "experiment.img" INFO: base address 0x800c000 INFO: length
0xf4000 DEBUG: writing "experiment.bin"

Op 14 sep. 2016 10:13 schreef "Travis Goodspeed" <notifications@github.com>:

**Comment by PD1LOI** [comment] 2016-09-14 08:45
Look here https://pd0zry.nl/md380-fw/

Op 14 sep. 2016 10:13 schreef "Travis Goodspeed" <notifications@github.com>:

**Comment by travisgoodspeed** [comment] 2016-09-14 08:48
Use the D13.020 firmware, not the S13.020 firmware.  S13.020 is only for GPS, and it does not work on radios without GPS.

`firmware-20160913-220001-a4523e2a.bin` will work fine.

`firmware-S13.020-20160913-220001-a4523e2a.bin` will not work.

Closing issue.

**Closed by travisgoodspeed** 2016-09-14 08:48 UTC

**Comment by PD1LOI** [comment] 2016-09-14 09:10
Yes i see the fault on my site.
Thanks

Op 14 sep. 2016 10:48 schreef "Travis Goodspeed" <notifications@github.com>:
